[tool.poetry]
name = "rec-engine"
version = "0.1.0"
description = ""
authors = ["Kirill Klimushin <kirklimushin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flake8 = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
